# Generated by Django 3.1.7 on 2021-03-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('region', models.CharField(choices=[('Adamawa', 'Adamawa'), ('Central', 'Central'), ('East', 'East'), ('Far North', 'Far North'), ('Littoral', 'Littoral'), ('North', 'North'), ('Northwest', 'Northwest'), ('South', 'South'), ('Southwest', 'Southwest'), ('West', 'West')], max_length=20)),
                ('town', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
